In [15]:
using StaticArrays, ImageFiltering

┌ Info: Precompiling ImageFiltering [6a3955dd-da59-5b1f-98d4-e7296123deb5]
└ @ Base loading.jl:1260


In [195]:
using Plots,Images, ImageView

┌ Info: Precompiling ImageView [86fae568-95e7-573e-a6b2-d8a6b900c9ef]
└ @ Base loading.jl:1260


In [368]:
using TestImages

using Cairo,Gtk
using Latexify

In [363]:
using BenchmarkTools


┌ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
└ @ Base loading.jl:1260


In [369]:
print(latexify("m*n"))

$m \cdot n$

In [159]:
function im2col(A, block_size) # mxn: block_size
            m,n = block_size
           M,N = size(A)
           mc = M-m+1          # no. vertical blocks
           nc = N-n+1          # no. horizontal blocks
           B = Array{eltype(A)}(undef, m*n, mc*nc)
           for j = 1:nc
             for i = 1:mc
               @views block = A[i:i+m-1, j:j+n-1]
               for k=1:m*n
                  B[k,(j-1)*mc+i] = block[k]
               end
             end
           end
           return B
       end

im2col (generic function with 2 methods)

In [160]:
function col2im(A,block_size)
    mm, nn = block_size
    return reshape(A, (mm, nn))
end

col2im (generic function with 2 methods)

In [161]:
B = reshape(collect(1:25),(5,5))'


5×5 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15
 16  17  18  19  20
 21  22  23  24  25

In [163]:
C = im2col(B, (5,5))

25×1 Array{Int64,2}:
  1
  6
 11
 16
 21
  2
  7
 12
 17
 22
  3
  8
 13
 18
 23
  4
  9
 14
 19
 24
  5
 10
 15
 20
 25

In [164]:
col2im(C,(5,5))

5×5 Array{Int64,2}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15
 16  17  18  19  20
 21  22  23  24  25

In [462]:

channelview(testimage("mandrill"))[1,:,:]

3×512×512 reinterpret(N0f8, ::Array{RGB{N0f8},3}):
[:, :, 1] =
 0.643  0.471  0.388  0.251  0.431  …  0.365  0.376  0.475  0.494  0.035
 0.588  0.49   0.29   0.31   0.329     0.388  0.451  0.58   0.663  0.043
 0.278  0.243  0.122  0.188  0.153     0.353  0.525  0.608  0.659  0.047

[:, :, 2] =
 0.247  0.529  0.518  0.588  0.51   …  0.361  0.463  0.482  0.459  0.039
 0.224  0.38   0.463  0.565  0.518     0.486  0.553  0.612  0.592  0.047
 0.122  0.129  0.18   0.224  0.18      0.478  0.549  0.588  0.592  0.043

[:, :, 3] =
 0.294  0.216  0.235  0.443  0.635  …  0.455  0.522  0.486  0.475  0.043
 0.169  0.137  0.161  0.384  0.518     0.58   0.627  0.588  0.533  0.059
 0.039  0.09   0.141  0.137  0.204     0.549  0.62   0.545  0.522  0.047

...

[:, :, 510] =
 0.459  0.478  0.463  0.294  0.239  …  0.373  0.337  0.431  0.286  0.02
 0.467  0.549  0.365  0.302  0.231     0.373  0.424  0.286  0.329  0.031
 0.267  0.384  0.353  0.18   0.224     0.278  0.357  0.235  0.267  0.02

[:, :, 511] =
 0

In [200]:

im2col(channelview(testimage("mandrill"))[1,:,:],(512, 512))

262144×1 Array{N0f8,2} with eltype Normed{UInt8,8}:
 0.643N0f8
 0.471N0f8
 0.388N0f8
 0.251N0f8
 0.431N0f8
 0.38N0f8
 0.239N0f8
 0.212N0f8
 0.251N0f8
 0.216N0f8
 0.212N0f8
 0.2N0f8
 0.196N0f8
 ⋮
 0.322N0f8
 0.373N0f8
 0.325N0f8
 0.267N0f8
 0.278N0f8
 0.329N0f8
 0.29N0f8
 0.349N0f8
 0.325N0f8
 0.318N0f8
 0.314N0f8
 0.016N0f8

In [222]:
function pad_constant(img,kernel,constant=0)
    kernel_h, kernel_w = size(kernel)
    img_h, img_w = size(img)
    padded_kernel= ones(img_h,img_w).*(1/(1+exp(-constant)));
    pad_h, pad_w = size(padded_kernel)
    center_x,center_y = pad_w ÷2, pad_h ÷2
    tmp_x = center_x-(kernel_w÷2)
    tmp_y = center_y-(kernel_h÷2)
    padded_kernel[collect(tmp_x:tmp_x+kernel_w-1),collect(tmp_y:tmp_y+kernel_h-1)] = kernel;
    return padded_kernel
end

pad_constant (generic function with 2 methods)

In [196]:
imshow(col2im(im2col(channelview(testimage("mandrill"))[1,:,:],(512, 512)),
(512, 512)))


(julia:1896465): Gtk-WARNING **: 22:14:13.478: Theme parsing error: gtk.css:9104:22: '/*' in comment block

(julia:1896465): Gtk-WARNING **: 22:14:13.480: Theme parsing error: gtk.css:10931:0: Expected a valid selector


Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}("window"=>GtkWindowLeaf(name="", parent, wi…
  "roi"         => Dict{String,Any}("redraw"=>37: "map(clim-mapped image, input…
  "annotations" => 3: "input-2" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 2: "CLim" = CLim{Normed{UInt8,8}}(0.0, 1.0) CLim{Normed{UInt…

In [201]:
using FFTW

In [219]:
img = channelview(testimage("mandrill"))[1,:,:];

In [220]:
img = convert.(Float32,img)

512×512 Array{Float32,2}:
 0.643137   0.247059   0.294118   …  0.458824   0.552941    0.701961
 0.470588   0.529412   0.215686      0.478431   0.533333    0.470588
 0.388235   0.517647   0.235294      0.462745   0.341176    0.376471
 0.25098    0.588235   0.443137      0.294118   0.356863    0.243137
 0.431373   0.509804   0.635294      0.239216   0.25098     0.313726
 0.380392   0.321569   0.701961   …  0.337255   0.545098    0.658824
 0.239216   0.27451    0.584314      0.713726   0.792157    0.65098
 0.211765   0.247059   0.45098       0.67451    0.419608    0.52549
 0.25098    0.262745   0.282353      0.545098   0.662745    0.466667
 0.215686   0.211765   0.2           0.341176   0.380392    0.596078
 0.211765   0.215686   0.372549   …  0.313726   0.305882    0.368627
 0.2        0.231373   0.356863      0.286275   0.388235    0.243137
 0.196078   0.231373   0.411765      0.286275   0.247059    0.407843
 ⋮                                ⋱             ⋮           
 0.560784   0.5254

In [221]:
imshow(img)

Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}("window"=>GtkWindowLeaf(name="", parent, wi…
  "roi"         => Dict{String,Any}("redraw"=>111: "map(clim-mapped image, inpu…
  "annotations" => 77: "input-26" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 76: "CLim" = CLim{Float32}(0.0, 1.0) CLim{Float32} 

In [223]:
kernel = rand(15, 15)

15×15 Array{Float64,2}:
 0.731564  0.67065    0.33955    0.0162717  …  0.868125   0.610576  0.283087
 0.884447  0.332166   0.126174   0.591551      0.557242   0.916682  0.162709
 0.225237  0.0770074  0.923544   0.776053      0.692071   0.254583  0.332156
 0.518578  0.417852   0.473367   0.302953      0.766679   0.684387  0.328251
 0.407969  0.388558   0.741347   0.506399      0.45745    0.493883  0.144527
 0.898691  0.482283   0.309024   0.520462   …  0.0725439  0.241748  0.533475
 0.465126  0.798104   0.257927   0.807132      0.550102   0.490976  0.662244
 0.564938  0.119881   0.111996   0.16864       0.854827   0.17676   0.618202
 0.191036  0.302235   0.0647027  0.684673      0.323148   0.940296  0.142913
 0.742474  0.191227   0.933384   0.096563      0.851548   0.126602  0.870332
 0.245919  0.292399   0.384466   0.688763   …  0.780014   0.371705  0.233357
 0.81841   0.454936   0.633638   0.48933       0.216536   0.443935  0.77582
 0.700633  0.41665    0.54953    0.545615      0.9030

In [224]:
kernel_padded = pad_constant(img, kernel)

512×512 Array{Float64,2}:
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  …  0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5     0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5     0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5     0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5     0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  …  0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5     0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5     0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5     0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5     0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  …  0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5     0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.

In [206]:
imshow(kernel_padded)

Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}("window"=>GtkWindowLeaf(name="", parent, wi…
  "roi"         => Dict{String,Any}("redraw"=>74: "map(clim-mapped image, input…
  "annotations" => 40: "input-14" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 39: "CLim" = CLim{Float64}(0.0102129, 0.997642) CLim{Float64…

In [225]:
flat_ker = im2col(kernel_padded, (512, 512));

In [227]:
flat_im = im2col(img, (512,512));

In [370]:
@time conv = ifft(fft(flat_im).*fft(flat_ker))


0.038521 seconds (190 allocations: 20.010 MiB)


262144×1 Array{Complex{Float64},2}:
 70622.60645434976 + 8.558134645137577e-8im
 70622.47815437838 - 6.258381384012658e-9im
 70622.32777927439 + 7.945017259538007e-9im
  70622.4856978972 + 1.1670681763444176e-7im
 70622.43406400015 + 2.204228719315508e-8im
 70622.46463714165 + 4.0708222131790155e-8im
 70622.27373051841 - 1.6821833555335407e-8im
 70622.30707697633 + 1.4448283369928154e-7im
 70622.68439267651 - 3.6181790798657776e-9im
 70622.51402114856 - 3.010846635173875e-8im
  70622.3992236888 + 4.4051844638518495e-8im
 70622.31367310684 - 3.186557476909364e-8im
 70622.13095088594 - 1.1032385689085611e-7im
                   ⋮
 70622.53727270706 - 6.830284886465638e-8im
 70622.62191410013 + 1.1076941161642594e-7im
 70622.63208585385 + 2.6883613690017226e-8im
 70622.80154153319 + 6.650665919816927e-8im
 70622.67940129325 - 3.130188942882523e-8im
 70622.88523502267 + 9.804242000063336e-9im
 70622.67947663346 - 4.28457462638645e-8im
 70622.65996999141 + 6.333984123161687e-8im
  70622.624

In [371]:
out1 = imshow(col2im(real.(conv),(512, 512)))

Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}("window"=>GtkWindowLeaf(name="", parent, wi…
  "roi"         => Dict{String,Any}("redraw"=>222: "map(clim-mapped image, inpu…
  "annotations" => 188: "input-62" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 187: "CLim" = CLim{Float64}(70618.2, 70625.4) CLim{Float64} 

In [372]:

function write_to_png(guidict, filename)
    canvas = guidict["gui"]["canvas"]
    ctx = getgc(canvas)
    Cairo.write_to_png(ctx.surface, filename)
end

write_to_png (generic function with 1 method)

In [374]:

write_to_png(out1, "/home/subhaditya/Desktop/GITHUB/SubhadityaMukherjee.github.io/img/deconstrucImages/imconv.png"

0

# Pooling

In [628]:
function maxpool(img, pool_size=2,stride = 2,depth=false)

    if depth == true
        input_d , input_h, input_w = size(img)
         output_h = Integer((input_h - pool_size)/stride )
        output_w = Integer((input_w - pool_size)/stride )
    
        result = zeros(input_d,output_h, output_w)  
        for i in collect(1:output_h),j in collect(1:output_w)  
            result[:, i,j] .= maximum(img[:, i*stride:i*stride+pool_size, j*stride:j*stride+pool_size])  
        end

    else
        input_h, input_w = size(img)
        output_h = Integer((input_h - pool_size)/stride )
        output_w = Integer((input_w - pool_size)/stride )
    
        result = zeros(output_h, output_w)  

        for i in collect(1:output_h),j in collect(1:output_w)
            result[i,j] = maximum(img[i*stride:i*stride+pool_size, j*stride:j*stride+pool_size])
        end
      
    
    end

    return result
end

maxpool (generic function with 4 methods)

In [629]:
temp =rand(3, 64, 64);

In [645]:
out3 = imshow(maxpool(img,10,2,false))

Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}("window"=>GtkWindowLeaf(name="", parent, wi…
  "roi"         => Dict{String,Any}("redraw"=>1128: "map(clim-mapped image, inp…
  "annotations" => 1094: "input-357" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 1093: "CLim" = CLim{Float64}(0.262745, 1.0) CLim{Float64} 

In [647]:
write_to_png(out3, "/home/subhaditya/Desktop/GITHUB/SubhadityaMukherjee.github.io/img/deconstrucImages/mp1.png")

0

In [648]:
function avgpool(img, pool_size=2,stride = 2,depth=false)

    if depth == true
        input_d , input_h, input_w = size(img)
         output_h = Integer((input_h - pool_size)/stride )
        output_w = Integer((input_w - pool_size)/stride )
    
        result = zeros(input_d,output_h, output_w)  

        for i in collect(1:output_h)
            for j in collect(1:output_w)
                temp = @view img[:, i*stride:i*stride+pool_size, j*stride:j*stride+pool_size]
                result[:, i,j] .= sum(temp)/prod(size(temp))
            end        
        end
    else
        input_h, input_w = size(img)
        output_h = Integer((input_h - pool_size)/stride )
        output_w = Integer((input_w - pool_size)/stride )
    
        result = zeros(output_h, output_w)  

        for i in collect(1:output_h)
            for j in collect(1:output_w)
                temp = @view img[i*stride:i*stride+pool_size, j*stride:j*stride+pool_size]
                #@show size(temp)
                result[i,j] = sum(temp)/prod(size(temp))
            end        
    end
    end

    return result
end

avgpool (generic function with 4 methods)

In [656]:
img = channelview(testimage("mandrill"));
out3 = imshow(avgpool(img,2,2,true))

Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}("window"=>GtkWindowLeaf(name="", parent, wi…
  "roi"         => Dict{String,Any}("redraw"=>1404: "map(clim-mapped image, inp…
  "annotations" => 1353: "input-444" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 1352: "CLim" = CLim{Float64}(0.165577, 0.681191) CLim{Float6…

In [652]:
write_to_png(out3, "/home/subhaditya/Desktop/GITHUB/SubhadityaMukherjee.github.io/img/deconstrucImages/ap1.png")

0